- hosts : web
  become: true
  gather_facts: no

  pre_tasks:
    - name: Install Python if not already present.
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Install AWS Cli
      apt:
        name: awscli

    - name: Log into aws ecr docker registry
      shell: "$(aws ecr get-login --no-include-email --region us-east-1)"

    - name: Deploy the app
      docker_container:
        name: simple-chat
        image: 385183906543.dkr.ecr.us-east-1.amazonaws.com/simple-chat:latest
        pull: true
        state: started
        recreate: true
        restart: true
        restart_policy: unless-stopped
        ports:
          - "3000:3000"
        
